import { PharmacyPurchaseOrderItem_DTO } from "./pharmacy-purchase-order-item.dto";
import { PharmacyVerificationActor } from "./pharmacy-verification-actor.dto";

export class PharmacyPurchaseOrder_DTO {
    public PurchaseOrderId: number = 0;
    public PurchaseOrderNo: number = 0;
    public PODate: string = '';
    public DeliveryDate: string = '';
    public SupplierId: number = 0;
    public POStatus: string = '';
    public SubTotal: number = 0;
    public TotalAmount: number = 0;
    public Remarks: string = null;
    public CreatedBy: number = 0;
    public CreatedOn: string = '';
    public CancelledBy: number = null;
    public CancelledOn: string = null;
    public CancelRemarks: string = "";
    public SupplierName: string = "";
    public VATAmount: number = 0;
    public IsCancel: boolean = false;
    public PurchaseOrderItems: Array<PharmacyPurchaseOrderItem_DTO> = new Array<PharmacyPurchaseOrderItem_DTO>();
    public IsVerificationEnabled: boolean = false;
    public CurrentVerificationLevel: number = 0;
    public MaxVerificationLevel: number = 0;
    public CurrentVerificationLevelCount: number = 0;
    public VerificationStatus: string = '';
    public IsVerificationAllowed: boolean = false;
    public IsModificationAllowed: boolean = true;
    public EmployeeName: string = null;
    public DiscountAmount: number = 0;
    public CCChargeAmount: number = 0;
    public IsActive: boolean = false;
    public TaxableAmount: number = 0;
    public NonTaxableAmount: number = 0;
    public DiscountPercentage: number = 0;
    public VATPercentage: number = 0;
    public CCChargeApplicableAmount: number = 0;
    public CCChargePercentage: number = 0;
    public VerificationRemarks: string = '';
    public DeliveryAddress: string = null;
    public InvoicingAddress: string = null;
    public DeliveryDays: number = 0;
    public Contact: string = null;
    public ContactNo: string = null;
    public ReferenceNo: string = null;
    public TransactionType: string = null;
    public VerifierList: PharmacyVerificationActor[] = [];
}