--change the db name of DEV_DanpheAdmin as per the environment--
--change the folder location:  C:\\DanpheHealthInc_PvtLtd_Files\Data\DbAudit\  as per the environment--

USE [DEV_DanpheAdmin] 
GO
-----START: NageshBB On 21 march 2018--Parameter updated-----------
--fix but of server audit creation when you run script first time on your system
Update SysAdmin_Parameters
set ParameterValue='C:\\DanpheHealthInc_PvtLtd_Files\Data\DbAudit\'
where ParameterName='SQLAuditFilePath'
Go
-----END: NageshBB On 21 march 2018--Parameter updated-----------
--------------start: for audit folder creation------
EXEC sp_configure 'show advanced options',1;
GO -- To update the currently configured value for advanced options.
RECONFIGURE;
GO -- To enable the feature. 
EXEC sp_configure 'xp_cmdshell',1;

GO -- To update the currently configured value for this feature.
RECONFIGURE;
GO
--Create Directory for save audit file
DECLARE @cmd sysname, @var sysname;  
SET @var = (select ParameterValue from SysAdmin_Parameters where ParameterName='SQLAuditFilePath');
SET @cmd = 'MD ' + @var;  
EXEC master..xp_cmdshell @cmd; 
GO
--------------end: for audit folder creation------


------start------------FOR Audit Specification and ServerAudit-------

USE [master]
GO
IF  EXISTS (SELECT * FROM sys.server_audits 
  WHERE name = N'DanpheH_SqlAudit')
BEGIN
 ALTER SERVER AUDIT DanpheH_SqlAudit WITH (STATE = OFF) 
 DROP SERVER AUDIT [DanpheH_SqlAudit]
END
GO
 
 ----trying to set dynamic path for MS_SQL_Server Audit--
-- ---not happening because of some error.. :(
--declare @AuditPath varchar(200)
--set @AuditPath=(select top 1 ParameterValue from sysadmin_parameters where parametername='SQLAuditFilePath')
----select  @AuditPath

CREATE SERVER AUDIT [DanpheH_SqlAudit]
TO FILE 
(	---FILEPATH = @AuditPath  -- this isn't working.. 
     FILEPATH =  N'C:\DanpheHealthInc_PvtLtd_Files\Data\DbAudit\'
	,MAXSIZE = 200 MB
	,MAX_ROLLOVER_FILES = 2
	,RESERVE_DISK_SPACE = ON
)
WITH
(	QUEUE_DELAY = 1000
	,ON_FAILURE = CONTINUE
)
GO
ALTER SERVER AUDIT [DanpheH_SqlAudit] WITH (STATE = ON)
GO
----------------------Creating a Server Audit Specification---------
-- drop server audit specification

IF  EXISTS (SELECT * FROM sys.server_audit_specifications 
  WHERE name = N'DanpheH_SqlAudit_Specification')
BEGIN
 ALTER SERVER AUDIT SPECIFICATION DanpheH_SqlAudit_Specification WITH (STATE = OFF) 
 DROP SERVER AUDIT SPECIFICATION [DanpheH_SqlAudit_Specification]
END
GO

 
IF (SELECT cast(left(cast(serverproperty('productversion') as varchar), 4) as decimal(5, 3))) < 11 
BEGIN 	 
	CREATE SERVER AUDIT SPECIFICATION [DanpheH_SqlAudit_Specification]
	FOR SERVER AUDIT [DanpheH_SqlAudit]
	ADD (APPLICATION_ROLE_CHANGE_PASSWORD_GROUP ),
	ADD (AUDIT_CHANGE_GROUP ),
	ADD (BACKUP_RESTORE_GROUP ),
	ADD (BROKER_LOGIN_GROUP ),
	ADD (DATABASE_CHANGE_GROUP),
	ADD (DATABASE_MIRRORING_LOGIN_GROUP ),
	ADD (DATABASE_OBJECT_ACCESS_GROUP ),
	ADD (DATABASE_OBJECT_CHANGE_GROUP ),
	ADD (DATABASE_OBJECT_OWNERSHIP_CHANGE_GROUP ),
	ADD (DATABASE_OBJECT_PERMISSION_CHANGE_GROUP),
	ADD (DATABASE_OPERATION_GROUP ),
	ADD (DATABASE_OWNERSHIP_CHANGE_GROUP),
	ADD (DATABASE_PERMISSION_CHANGE_GROUP ),
	ADD (DATABASE_PRINCIPAL_CHANGE_GROUP),
	ADD (DATABASE_PRINCIPAL_IMPERSONATION_GROUP ),
	ADD (DATABASE_ROLE_MEMBER_CHANGE_GROUP),
	ADD (DBCC_GROUP ),
	ADD (FAILED_LOGIN_GROUP ),
	ADD (FULLTEXT_GROUP ),
	ADD (LOGIN_CHANGE_PASSWORD_GROUP),
	ADD (LOGOUT_GROUP ),
	ADD (SCHEMA_OBJECT_ACCESS_GROUP ),
	ADD (SCHEMA_OBJECT_CHANGE_GROUP ),
	ADD (SCHEMA_OBJECT_OWNERSHIP_CHANGE_GROUP ),
	ADD (SCHEMA_OBJECT_PERMISSION_CHANGE_GROUP),
	ADD (SERVER_OBJECT_CHANGE_GROUP ),
	ADD (SERVER_OBJECT_OWNERSHIP_CHANGE_GROUP ),
	ADD (SERVER_OBJECT_PERMISSION_CHANGE_GROUP),
	ADD (SERVER_OPERATION_GROUP ),
	ADD (SERVER_PERMISSION_CHANGE_GROUP ),
	ADD (SERVER_PRINCIPAL_CHANGE_GROUP),
	ADD (SERVER_PRINCIPAL_IMPERSONATION_GROUP ),
	ADD (SERVER_ROLE_MEMBER_CHANGE_GROUP),
	ADD (SERVER_STATE_CHANGE_GROUP),
	ADD (SUCCESSFUL_LOGIN_GROUP ),
	ADD (TRACE_CHANGE_GROUP )
	WITH (STATE = ON)
	
	END 
 
ELSE 
 
	BEGIN 
 
	CREATE SERVER AUDIT SPECIFICATION [DanpheH_SqlAudit_Specification]
	FOR SERVER AUDIT [DanpheH_SqlAudit]
	ADD (APPLICATION_ROLE_CHANGE_PASSWORD_GROUP),
	ADD (AUDIT_CHANGE_GROUP),
	ADD (BACKUP_RESTORE_GROUP),
	ADD (BROKER_LOGIN_GROUP),
	ADD (DATABASE_CHANGE_GROUP ),
	ADD (DATABASE_LOGOUT_GROUP ),
	ADD (DATABASE_MIRRORING_LOGIN_GROUP),
	ADD (DATABASE_OBJECT_ACCESS_GROUP),
	ADD (DATABASE_OBJECT_CHANGE_GROUP),
	ADD (DATABASE_OBJECT_OWNERSHIP_CHANGE_GROUP),
	ADD (DATABASE_OBJECT_PERMISSION_CHANGE_GROUP ),
	ADD (DATABASE_OPERATION_GROUP),
	ADD (DATABASE_OWNERSHIP_CHANGE_GROUP ),
	ADD (DATABASE_PERMISSION_CHANGE_GROUP),
	ADD (DATABASE_PRINCIPAL_CHANGE_GROUP ),
	ADD (DATABASE_PRINCIPAL_IMPERSONATION_GROUP),
	ADD (DATABASE_ROLE_MEMBER_CHANGE_GROUP ),
	ADD (DBCC_GROUP),
	ADD (FAILED_DATABASE_AUTHENTICATION_GROUP),
	ADD (FAILED_LOGIN_GROUP),
	ADD (FULLTEXT_GROUP),
	ADD (LOGIN_CHANGE_PASSWORD_GROUP ),
	ADD (LOGOUT_GROUP),
	ADD (SCHEMA_OBJECT_ACCESS_GROUP),
	ADD (SCHEMA_OBJECT_CHANGE_GROUP),
	ADD (SCHEMA_OBJECT_OWNERSHIP_CHANGE_GROUP),
	ADD (SCHEMA_OBJECT_PERMISSION_CHANGE_GROUP ),
	ADD (SERVER_OBJECT_CHANGE_GROUP),
	ADD (SERVER_OBJECT_OWNERSHIP_CHANGE_GROUP),
	ADD (SERVER_OBJECT_PERMISSION_CHANGE_GROUP ),
	ADD (SERVER_OPERATION_GROUP),
	ADD (SERVER_PERMISSION_CHANGE_GROUP),
	ADD (SERVER_PRINCIPAL_CHANGE_GROUP ),
	ADD (SERVER_PRINCIPAL_IMPERSONATION_GROUP),
	ADD (SERVER_ROLE_MEMBER_CHANGE_GROUP ),
	ADD (SERVER_STATE_CHANGE_GROUP ),
	ADD (SUCCESSFUL_DATABASE_AUTHENTICATION_GROUP),
	ADD (SUCCESSFUL_LOGIN_GROUP),
	ADD (TRACE_CHANGE_GROUP),
	ADD (USER_CHANGE_PASSWORD_GROUP),
	ADD (USER_DEFINED_AUDIT_GROUP)
	WITH (STATE = ON)
 
	
    END
	-------database audit specification--------
/*
This section will iterate in every database and will create the database audit specifications 
 
*/
 
IF (SELECT cast(left(cast(serverproperty('productversion') as varchar), 4) as decimal(5, 3))) < 11 
BEGIN 
	EXEC sp_MSforeachdb 'USE [?] 
	IF  EXISTS (SELECT * FROM sys.database_audit_specifications WHERE name = N''DatabaseAuditSpecification'')
	BEGIN
	 ALTER DATABASE AUDIT SPECIFICATION DatabaseAuditSpecification WITH (STATE = OFF)
	 DROP DATABASE AUDIT SPECIFICATION DatabaseAuditSpecification
	END
 
	CREATE DATABASE AUDIT SPECIFICATION [DatabaseAuditSpecification]
	FOR SERVER AUDIT [DanpheH_SqlAudit]
	ADD (APPLICATION_ROLE_CHANGE_PASSWORD_GROUP ),
	ADD (AUDIT_CHANGE_GROUP ),
	ADD (BACKUP_RESTORE_GROUP ),
	ADD (DATABASE_CHANGE_GROUP),
	ADD (DATABASE_OBJECT_ACCESS_GROUP ),
	ADD (DATABASE_OBJECT_CHANGE_GROUP ),
	ADD (DATABASE_OBJECT_OWNERSHIP_CHANGE_GROUP ),
	ADD (DATABASE_OBJECT_PERMISSION_CHANGE_GROUP),
	ADD (DATABASE_OPERATION_GROUP ),
	ADD (DATABASE_OWNERSHIP_CHANGE_GROUP),
	ADD (DATABASE_PERMISSION_CHANGE_GROUP ),
	ADD (DATABASE_PRINCIPAL_CHANGE_GROUP),
	ADD (DATABASE_PRINCIPAL_IMPERSONATION_GROUP ),
	ADD (DATABASE_ROLE_MEMBER_CHANGE_GROUP),
	ADD (DBCC_GROUP ),
	ADD (SCHEMA_OBJECT_ACCESS_GROUP ),
	ADD (SCHEMA_OBJECT_CHANGE_GROUP ),
	ADD (SCHEMA_OBJECT_OWNERSHIP_CHANGE_GROUP ),
	ADD (SCHEMA_OBJECT_PERMISSION_CHANGE_GROUP)
	WITH (STATE = ON)'
END
 
ELSE 
 
BEGIN
	EXEC sp_MSforeachdb 'USE [?]
	IF  EXISTS (SELECT * FROM sys.database_audit_specifications WHERE name = N''DatabaseAuditSpecification'')
	BEGIN
	 ALTER DATABASE AUDIT SPECIFICATION DatabaseAuditSpecification WITH (STATE = OFF)
	 DROP DATABASE AUDIT SPECIFICATION DatabaseAuditSpecification
	END
 
	CREATE DATABASE AUDIT SPECIFICATION [DatabaseAuditSpecification]
	FOR SERVER AUDIT [DanpheH_SqlAudit]
	ADD (APPLICATION_ROLE_CHANGE_PASSWORD_GROUP ),
	ADD (AUDIT_CHANGE_GROUP ),
	ADD (BACKUP_RESTORE_GROUP ),
	ADD (DATABASE_CHANGE_GROUP),
	ADD (DATABASE_LOGOUT_GROUP),
	ADD (DATABASE_OBJECT_ACCESS_GROUP ),
	ADD (DATABASE_OBJECT_CHANGE_GROUP ),
	ADD (DATABASE_OBJECT_OWNERSHIP_CHANGE_GROUP ),
	ADD (DATABASE_OBJECT_PERMISSION_CHANGE_GROUP),
	ADD (DATABASE_OPERATION_GROUP ),
	ADD (DATABASE_OWNERSHIP_CHANGE_GROUP),
	ADD (DATABASE_PERMISSION_CHANGE_GROUP ),
	ADD (DATABASE_PRINCIPAL_CHANGE_GROUP),
	ADD (DATABASE_PRINCIPAL_IMPERSONATION_GROUP ),
	ADD (DATABASE_ROLE_MEMBER_CHANGE_GROUP),
	ADD (DBCC_GROUP ),
	ADD (FAILED_DATABASE_AUTHENTICATION_GROUP ),
	ADD (SCHEMA_OBJECT_ACCESS_GROUP ),
	ADD (SCHEMA_OBJECT_CHANGE_GROUP ),
	ADD (SCHEMA_OBJECT_OWNERSHIP_CHANGE_GROUP ),
	ADD (SCHEMA_OBJECT_PERMISSION_CHANGE_GROUP),
	ADD (SUCCESSFUL_DATABASE_AUTHENTICATION_GROUP ),
	ADD (USER_CHANGE_PASSWORD_GROUP ),
	ADD (USER_DEFINED_AUDIT_GROUP )
	WITH (STATE = ON)'
END
GO
---------------end:---FOR Audit Specification and ServerAudit-------
