import * as moment from "moment";
import { PHRMEmployeeCashTransaction } from "../../shared/pharmacy-employee-cash-transaction";
import { PHRMPatientConsumptionItem } from "./phrm-patient-consumption-item.model";

export class PHRMPatientConsumption {
    public PatientConsumptionId: number = 0;
    public FiscalYearId: number = 0;
    public PatientId: number = 0;
    public PatientVisitId: number = 0;
    public SubTotal: number = 0;
    public DiscountAmount: number = 0;
    public TotalAmount: number = 0;
    public BillingStatus: string = "";
    public SchemeId: number = 1;
    public StoreId: number = 0;
    public CreatedBy: number = 0;
    public CreatedOn: string = moment().format('YYYY-MM-DD');
    public ModifiedBy: number = null;
    public ModifiedOn: string = "";
    public HospitalNo: string = "";
    public PatientName: string = "";
    public Age: string = "";
    public Sex: String = "";
    public ContactNo: string = "";
    public IsActive: boolean = false;
    public Address: string = "";
    public IpNo: string = null;
    public ConsumptionReceiptNo: number = 0;
    public PaymentMode: string = "cash";
    public UserName: string = "";
    public PatientConsumptionItems: Array<PHRMPatientConsumptionItem> = new Array<PHRMPatientConsumptionItem>();
    public DiscountPercentage: number = 0;
    public Tender: number = 0;
    public Change: number = 0;
    public Remark: string = '';
    public ConsumptionReturnReceiptNo: number = 0;
    public ConsumptionReturnItemIds: Array<number> = new Array<number>();
    public InvoicePrintNo: number = 0;
    public FinalizedDate: string = moment().format('YYYY-MM-DD');
    public ReturnedAmount: number = 0;
    public SalePrice: number = 0;
    public VisitType: string = '';
    public CounterId: number = 0;
    public PrescriberId: number = null;
    public ReceivedAmount: number = 0;
    public CoPaymentCashAmount: number = 0;
    public CoPaymentCreditAmount: number = 0;
    CoPaymentMode: string = null;
    IsCoPayment: boolean = false;
    Copayment_CashPercent: number = 0;
    Copayment_CreditPercent: number = 0;
    PaymentDetails: string = null;
    OrganizationId: number = null;
    CreditOrganizationName: string = null;
    PaidAmount: number = 0;
    public PHRMEmployeeCashTransactions: Array<PHRMEmployeeCashTransaction> = new Array<PHRMEmployeeCashTransaction>();
    DepositUsed: number = 0;
    ClaimCode: number = null;
    DepositDeductAmount: number = 0;
    PriceCategoryId: number = null;
    IsDiscountApplicable: boolean = false;
    MedCertificationNo: string = null;
}
